- name: Login to Cyber Recovery
  uri:
    url: "{{ api_base_url }}/v8/login"
    method: POST
    body_format: json
    body: "{{ login_payload }}"
    headers:
      Content-Type: "application/json"
    status_code: 200
  register: login_response

- name: Logout user
  uri:
    url: "{{ api_base_url }}/v8/logout/{{ user_id }}"
    method: POST
    headers:
      X-CR-REFRESH-TOKEN: "{{ refresh_token }}"
    status_code: 200
