---
- name: Login and create policies in Cyber Recovery
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./vars/main.yml
  tasks:
    - name: Include login role
      import_role:
        name: authentication
        tasks_from: login
      vars:
        login_payload: "{{ my_login_payload }}"      

    - name: Set access token from login response
      set_fact:
        auth_token: "{{ login_response.json.accessToken }}"

    - name: Run only the create_policies task from policies role
      import_role:
        name: policies
        tasks_from: create
      vars:
        new_policies: "{{ my_new_policy }}"

    - name: Show create policies response
      debug:
        msg: "{{ create_policies_response.json }}"
