---
- name: Login and create storage in Cyber Recovery
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./vars/main.yml
  tasks:
    - name: Include login role
      include_role:
        name: login
      vars:
        login_payload: "{{ my_login_payload }}"      

    - name: Set access token from login response
      set_fact:
        auth_token: "{{ login_response.json.accessToken }}"

    - name: Run only the create_storage task from storage role
      import_role:
        name: storage
        tasks_from: create
      vars:
        new_storage: "{{ my_new_storage }}"

