---
- name: Login and create storage in Cyber Recovery
  hosts: localhost
  gather_facts: no
  vars:
    api_base_url: "https://cr.demo.local:14778/cr"
    my_login_payload:
      username: "cradmin"
      password: "Ithaca2022!"
#      securitycode: "123456"  # Optional if MFA is disabled

    my_storage:
      nickname: "MyVaultDD"
      hostinfo:
        hostname: "vault-dd.demo.local"
        hostUsername: "sysadmin"
        hostPassword: "Password123!"
        sshPort: 22

  tasks:
    - name: Include login role
      include_role:
        name: login
      vars:
        login_payload: "{{ my_login_payload }}" 
    - name: Set access token from login response
      set_fact:
        auth_token: "{{ login_response.json.accessToken }}"


    - import_role:
        name: storage
        vars:
          auth_token: "{{ auth_token }}"
      tasks_from: get  
      tags: get_storage
