---
- name: Login and create storage in Cyber Recovery
  hosts: localhost
  gather_facts: no
  vars:
    api_base_url: "https://cr.demo.local"
    login_payload:
      username: "cradmin"
      password: "Ithaca2022!"
#      securitycode: "123456"  # Optional if MFA is disabled

    new_storage:
      nickname: "MyVaultDD"
      hostinfo:
        hostname: "vault-dd.demo.local"
        hostUsername: "sysadmin"
        hostPassword: "Password123!"
        sshPort: 22


  tasks:
    - name: Login to Cyber Recovery
      uri:
        url: "{{ api_base_url }}/v8/login"
        method: POST
        body_format: json
        body: "{{ login_payload }}"
        headers:
          Content-Type: "application/json"
        status_code: 200
      register: login_response

    - name: Extract access token
      set_fact:
        access_token: "{{ login_response.json.accessToken }}"

    - name: Create new storage endpoint
      uri:
        url: "{{ api_base_url }}/v8/storage"
        method: POST
        body_format: json
        body: "{{ new_storage }}"
        headers:
          Content-Type: "application/json"
          X-CR-AUTH-TOKEN: "{{ access_token }}"
        status_code: 201
      register: storage_creation

    - name: Show storage creation result
      debug:
        var: storage_creation
