---
- name: Login and create storage in Cyber Recovery
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./vars/main.yml

  tasks:
    - name: Include login role
      import_role:
        name: authentication
        tasks_from: login
      vars:
        login_payload: "{{ my_login_payload }}" 
    - name: Set access token from login response
      set_fact:
        auth_token: "{{ login_response.json.accessToken }}"

    - name: Run  get_mtree task from storage role
      include_role:
        name: storage
        tasks_from: get_mtree

    - ansible.builtin.debug:
        msg: "{{ get_storagemtree_response  | json_query('json.items[*]') }}"
        verbosity: 1  
                
