---
- name: Login to Cyber Recovery
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./vars/main.yml
  tasks:
    - name: Include login role
      import_role:
        name: authentication
        task_from: login
      vars:
        login_payload: "{{ my_login_payload }}"      

    - name: Set access token from login response
      set_fact:
        auth_token: "{{ login_response.json.accessToken }}"