
galaxy_info:
  author: Karsten Bott
  description: Manage storage endpoints in Cyber Recovery
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
        - 9
        - 10
        - 11
    - name: Rocky
      versions:
        - 8
        - 9
        - 10
    - name: AlmaLinux
      versions:
        - 8
        - 9
        - 10
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
        - lunar
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
        - trixie