name: Generate Ansible Roles Manifest

on:
  push:
    paths:
      - "roles/**"
      - ".github/scripts/generate_manifest.py"
  workflow_dispatch:

permissions:
  contents: write  # ✅ Required for GITHUB_TOKEN to push changes

jobs:
  generate-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Run manifest generator
        run: python .github/scripts/generate_manifest.py

      - name: Commit and push manifest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Karsten Bott"
          git config --global user.email "karsten.bott@bottnet.de"
          git add ansible_roles_manifest.json
          git diff --cached --quiet || (
            git commit -m "Update roles manifest [auto]" &&
            git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}"
          )
